### ISSUE TITLE
Support 1.36.0

### ISSUE THREAD

**Issue by justinmoon** [bbqsrc/bare-io#2]
Hey. I'm trying to add `no_std` support to [rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin) and your library has been helpful.

We'd like to have an optional feature that worked in `no_std` with an allocator in using `1.36.0` -- the version `alloc` stabilized.

But it seems you're using the `non_exhaustive` attribute, which stabilized in `1.40.0`. Would it be possible to accommodate this usecase?

**Comment by bbqsrc** [comment]
This project only supports 1.47, as stated in the README. When I have time I will bump that to 1.48. We track the current stable release, and this will continue until we have determined a sustainable maintainability policy for other versions.

I would suggest that if this is an immediate need of yours that you fork the project for your use case. Thanks!
